/*
 * mutos_cpp.h - shared declarations for the MUTOS 1700 cross C preprocessor.
 *
 * mutos_cpp re-implements the observable behavior of the real MUTOS
 * 1700 / V7 "fast cpp" (v7/cpp/cpp.c, written by John F. Reiser, 1978)
 * in clean, modern C11 - matching this project's established approach
 * for mutos_as/mutos_ld: not a literal transliteration of the original
 * pointer-arithmetic-heavy K&R source, but a from-scratch implementation
 * validated byte-for-byte against real reference output.
 *
 * See src/mutos_cpp/README (or STATUS.md) for the behavioral spec this
 * was reverse-engineered from, including the deliberate deviations from
 * "standard" ANSI cpp that this K&R-era variant exhibits (no #elif, no
 * # / ## operators, #if identifiers are a defined-or-not boolean test
 * rather than macro-value substitution, false #ifdef/#ifndef/#if bodies
 * produce ZERO output lines rather than blank placeholder lines, etc).
 */

#ifndef MUTOS_CPP_H
#define MUTOS_CPP_H

#include <stdio.h>
#include <stdbool.h>
#include <stddef.h>

/* ------------------------------------------------------------------ */
/* Limits (generous; this is a host tool, not the original PDP-11/8086
 * resource-constrained cpp, so we do not need V7's tight SBSIZE/symsiz
 * budgets - just sane upper bounds to catch runaway/malformed input). */
#define MCPP_MAX_INCLUDE_DEPTH   32
#define MCPP_MAX_MACRO_PARAMS    64
#define MCPP_MAX_INCLUDE_DIRS    32
#define MCPP_MAX_PATH            1024

/* ------------------------------------------------------------------ */
/* Macro body representation: a macro's replacement text is stored as a
 * sequence of pieces - literal text runs and formal-parameter
 * references - so substitution is a simple linear walk with no need to
 * re-derive parameter boundaries at expansion time. */

typedef struct MacroBodyPiece {
    char *literal;     /* literal text (owned), or NULL if this piece is
                         * a parameter reference */
    int   param_index; /* index into the macro's params[] array, or -1
                         * if this piece is a literal-text run */
    struct MacroBodyPiece *next;
} MacroBodyPiece;

typedef struct Macro {
    char  *name;
    bool   is_function_like;
    int    nparams;
    char  *params[MCPP_MAX_MACRO_PARAMS];
    MacroBodyPiece *body;   /* linked list, may be NULL/empty for a
                              * macro defined with no replacement text */
    bool   hidden;          /* "blue paint": true while this macro's own
                              * expansion is being re-scanned, to stop
                              * direct/indirect self-recursion */
    struct Macro *next;     /* hash-bucket chaining */
} Macro;

/* ------------------------------------------------------------------ */
/* Source stack: either a real file (opened for an #include, or the
 * initial input file) or a "pushback" in-memory buffer holding text
 * generated by macro expansion, to be re-scanned for further macro
 * calls exactly like ordinary source text. */

typedef enum { SRC_FILE, SRC_BUFFER } SourceKind;

typedef struct Source {
    SourceKind kind;

    /* SRC_FILE fields */
    FILE *fp;
    char *filename;     /* owned copy, used for diagnostics */
    char *dir;           /* directory containing this file, owned copy,
                           * used to resolve sibling "..." includes */
    int   lineno;

    /* SRC_BUFFER fields */
    char  *buf;          /* owned */
    size_t buf_len;
    size_t buf_pos;
    Macro *hidden_macro;  /* macro to un-hide when this buffer is fully
                            * consumed and popped (may be NULL) */

    /* Pushback (ungetc) is scoped per-source, not global: a character
     * peeked while this source was on top must stay associated with
     * THIS source, so that pushing a new source (e.g. for a macro
     * expansion found via that peek) doesn't let it "leak" ahead of
     * the new source's own content. */
    int    pushback[8];
    int    pushback_n;

    struct Source *parent;
} Source;

/* ------------------------------------------------------------------ */
/* Conditional-compilation nesting stack (#ifdef/#ifndef/#if/#else/#endif) */

typedef struct CondFrame {
    bool parent_active; /* were we active (all ancestors true) when this
                          * frame's condition was tested? */
    bool this_true;     /* is *this* frame's branch currently the taken
                          * one? (flips once on #else) */
    bool else_seen;      /* to catch/ignore a duplicate #else */
    struct CondFrame *prev;
} CondFrame;

/* ------------------------------------------------------------------ */
/* Global preprocessor state (single translation unit; mutos_cpp, like
 * the original, processes exactly one primary input at a time). */

typedef struct CppState {
    Source    *src;          /* top of source stack */
    CondFrame *cond;         /* top of conditional-nesting stack */
    bool       at_line_start; /* true iff the next raw char would begin a
                                * fresh physical line (for '#' directive
                                * recognition - column 1 only, matching
                                * the real MUTOS/V7 fast-cpp) */


    Macro    **macros;        /* hash table, chained */
    size_t     macro_table_size;

    FILE      *out;

    /* CLI-controlled options */
    bool       pflag;         /* -P: suppress "# N \"file\"" line markers
                                * (always effectively true for us since
                                * we never emit them - see README) */
    bool       cflag;         /* -C: keep comments instead of deleting */
    bool       rflag;         /* -R: allow unbounded macro recursion
                                * (we still guard via hide-sets even
                                * with -R, for host-process safety) */

    char      *include_dirs[MCPP_MAX_INCLUDE_DIRS];
    int        n_include_dirs;

    int        include_depth;
    int        exit_status;   /* nonzero if any error was reported */
} CppState;

/* ------------------------------------------------------------------ */
/* source.c */
bool source_push_file(CppState *cs, const char *path, const char *dir);
void source_pop(CppState *cs);
int  source_getc(CppState *cs);   /* returns EOF at true end of all input;
                                    * applies backslash-newline splicing */
int  source_peekc(CppState *cs);
int  source_peekc2(CppState *cs); /* peek one further ahead than peekc */
void source_ungetc(CppState *cs, int c);
void source_push_buffer(CppState *cs, char *text, size_t len, Macro *hidden_owner);
int  cur_lineno(CppState *cs);
const char *cur_filename(CppState *cs);

/* ------------------------------------------------------------------ */
/* macro.c */
unsigned macro_hash(const char *name, size_t table_size);
Macro *macro_lookup(CppState *cs, const char *name);
void   macro_undef(CppState *cs, const char *name);
void   macro_table_init(CppState *cs, size_t size);
void   macro_free_all(CppState *cs);

/* Parses a #define directive's tail (already positioned right after the
 * macro name). `active` is this directive's pre-state (see directive.c) -
 * when false the macro is fully parsed (so the source is correctly
 * consumed and any embedded multi-line comment is accounted for) but
 * discarded rather than installed. */
void   macro_do_define(CppState *cs, const char *name, bool active);

/* Attempts to expand a function-/object-like macro call starting at the
 * identifier `name`. On success, pushes the substituted text as a new
 * source buffer and returns true. On failure (e.g. function-like macro
 * not followed by '('), returns false and performs no input consumption
 * beyond what's needed to peek ahead. */
bool macro_try_expand(CppState *cs, const char *name);

/* ------------------------------------------------------------------ */
/* ifexpr.c */
long ifexpr_eval(CppState *cs, bool *ok);

/* ------------------------------------------------------------------ */
/* directive.c */
void directive_dispatch(CppState *cs);
bool cond_active(CppState *cs);

/* ------------------------------------------------------------------ */
/* scan.c */
void scan_run(CppState *cs);

/* ------------------------------------------------------------------ */
/* diagnostics (implemented in main.c) */
void cpp_error(CppState *cs, const char *fmt, ...);
void cpp_warn(CppState *cs, const char *fmt, ...);

/* ------------------------------------------------------------------ */
/* small shared helpers (util.c) */
char *xstrdup(const char *s);
char *xstrndup(const char *s, size_t n);
bool  is_ident_start(int c);
bool  is_ident_cont(int c);
char *read_identifier_from_source(CppState *cs); /* assumes an
                                                    * identifier-start
                                                    * char is next */
void  skip_hspace_only(CppState *cs); /* spaces/tabs only, no comments,
                                        * no newlines */
const char *cur_dir(CppState *cs);
char *dir_of(const char *path); /* caller frees */

#endif /* MUTOS_CPP_H */
